### ISSUE TITLE
Reactive edge configuration

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#191]
Implement live config.yaml file sync and reload on change.

Currently changes to config.yaml require restart. It is harder to implement robust config sync with proper graceful state transitions, but it may pay off long term as we move towards API and UI driven config changes.

See #190 as a related topic.

**Comment by ivelin** [comment]
@muka does dynaconf resolve this feature request with https://github.com/ambianic/ambianic-edge/pull/222?

**Comment by muka** [comment]
Not directly but there is a dedicated implementation with `wathcdog`. The implementation has been simplified so that the server will restart if the configuration file is changed on fs.

**Comment by ivelin** [comment]
Then I will close this issue if you are OK with that @muka ?

**Comment by muka** [comment]
Yes close thanks!
