### ISSUE TITLE
[FEATURE] Camera IP changes without notification

### ISSUE THREAD

**Issue by njcurtis3** [ambianic/ambianic-edge#198]
NOTE: This issue is related to #161 

Problem:
IP address of the wifi camera changed. In this case, the new IP address is different from the one manually configured in the config.yaml file. This requires the user to find the new IP address in native camera app, then go to the config file to manually change it. 

Desired State:
In the next iteration, there will be support for ONVIF which has a way to advertise the Camera IP and capabilities.
We want the IP to update automatically

**Comment by ivelin** [comment]
Valid issue. Related to #161
