### ISSUE TITLE
[BUG] Raspicam support issue

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#212]
**Describe the bug**
John Senay and @muka observed a strange horizontal distortion. See attached example. I suspect it's an issue with the gstreamer driver for raspicam because the regular raspistill command works fine.

**Expected behavior**

**Screenshots**
![screenshot_from_2020-08-12_09-34-56](https://user-images.githubusercontent.com/2234901/91460898-01973000-e84e-11ea-9726-ca286f9c8635.png)

**Solution***

Luca and I discussed using directly the raspicam library and not going through gstreamer.

**Comment by muka** [comment]
The PR with wokring implementation is available in #214

**Comment by muka** [comment]
Can this issue be closed?

**Comment by ivelin** [comment]
Great. Is there a doc update related to #214 : How to install, configure and test a picam on ambianic edge?

**Comment by muka** [comment]
Yes it's documented in the supported source types

**Comment by ivelin** [comment]
Great. I saw that now: https://docs.ambianic.ai/users/configure/
