### ISSUE TITLE
Clean up ai_models dir

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#213]
https://github.com/ambianic/ambianic-edge/tree/master/ai_models

There are models that aren't used and create unnecessary dead weight for the release packages. We should trim out mobilenet_v1 and other outdated files that noone seems to use.

**Comment by njcurtis3** [comment]
Suggestions of models to delete:
inception_v1_224_quant.tflite
inception_v2_224_quant.tflite
inception_v2_224_quant_edgetpu.tflite 
inception_v3_299_quant.tflite 
inception_v3_299_quant_edgetpu.tflite 

mobilenet_ssd_v1_coco_quant_postprocess.tflite 
mobilenet_ssd_v1_coco_quant_postprocess_edgetpu.tflite

mobilenet_v1_1.0_224_quant.tflite
mobilenet_v1_1.0_224_quant_edgetpu.tflite 
mobilenet_v1_1.0_224_quant_embedding_extractor.tflite
mobilenet_v1_1.0_224_quant_embedding_extractor_edgetpu.tflite

Keep other instances of the mobilenet_V2 models for insect,bird, and plant. 

Add suggestions:
Mobilenet_V3
ResNet50
VGG16
Posenet 
Inception V3

**Comment by ivelin** [comment]
Makes sense. Would you like to push a PR for the cleanup part?
We should open separate issues to test and track new model additions.

**Comment by njcurtis3** [comment]
Yes will push a PR soon. 

Should we make an `"Archived Models"` folder instead of deleting these? If so, should it sit in the `ai_models` folder?

**Comment by ivelin** [comment]
I don't think we need to archive models. The outdated ones are usually replaced by newer better performing ones every so often.

**Comment by njcurtis3** [comment]
Ok makes sense

**Comment by njcurtis3** [comment]
pushed PR

**Comment by ivelin** [comment]
Thank you, @njcurtis3 . Merged.
