### ISSUE TITLE
Wifi setup using Picam and QR code scan

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#216]
**Is your feature request related to a problem? Please describe.**
It currently requires some programming skills (docker and shell) to setup an Ambianic system.
We would like to make it straightforward for consumers to install and run without coding skills.

One of the key challenges in the setup process is getting the Ambiniac Edge device connected to the Internet.

**Describe the solution you'd like**
We've explored Bluetooth and WiFi hotspot as possible solutions for initial Ambianic Edge setup. It turns out Bluetooth is flimsy and not well supported in browsers. As of Sep 2020 only Chrome supports an experimental BLE API.

The team discussed and settled on the option to use a picam attached to the rpi Ambianic Edge device to scan QR code presented to it by the Ambianic UI (PWA). The QR code would contain the local WiFi connectivity credentials that the pi can use hop on the Internet.

**Describe alternatives you've considered**
We've considered Bluetooth and Wifi hotspot.

**Additional context**
There is a standard way to share wifi access via QR Code:
https://www.qr-code-generator.com/solutions/wifi-qr-code/

QR code scanner example on rpi via pyzbar lib:
https://circuitdigest.com/microcontroller-projects/qr-code-scanner-using-raspberry-pi-and-opencv

On the client side, Android has a built-in ability to share Wifi access via QR Code:
https://www.cnet.com/how-to/android-10-share-a-wi-fi-password-in-a-snap-with-a-qr-code/

For iOS, it's not built in, but there are alternatives:
https://www.zdnet.com/article/how-to-easily-share-your-wi-fi-network-with-iphones-and-ipads-and-with-a-bit-more-hassle-android-devices-too/

**Comment by muka** [comment]
On this side we miss the qrcode detection. Is it still required as we use the wifi  captive approach?

**Comment by ivelin** [comment]
I vote to close this issue until we have evidence that the wifi setup is not good enough for users.
