### ISSUE TITLE
[BUG] Config manager tests fail intermittently in CI

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#221]
**Describe the bug**
https://travis-ci.com/github/ambianic/ambianic-edge/jobs/428986996#L3721

When the CI job is rerun a few times it eventually passes, but the config test is not reliable. It seems to be related to the library that is supposed to detect file system changes.

**Comment by muka** [comment]
I can take care of this in the next iteration, also simplifying the implementation

**Comment by muka** [comment]
Done, switched to `watchdog` in PR #222

**Comment by ivelin** [comment]
Awesome. Thanks. Closing.

We have a related issue now with auto upgrade for users who are on the old config file format. See #224.
