### ISSUE TITLE
cleanup pose engine loose ends

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#252]
@bhavikapanara as I am integrating the fall detection model with the UI and the rest of the system, I am finding loose ends that need to be cleaned up.

For example I see that the Pose Engine implementation has hardcoded values [257,257] for input tensor size instead of calculating based on the model details. Can you please take a look and comment?
https://github.com/ambianic/ambianic-edge/blob/482d9774306ad7700a7cb905ac89c6949ed0cf4a/src/ambianic/pipeline/ai/pose_engine.py#L87

Another potential issue is this resizing of the image. If I am not mistaken, it changes the width and height proportions, which may confuse the AI model as the people are no longer in their natural proportions. [See here](https://github.com/ambianic/ambianic-edge/blob/482d9774306ad7700a7cb905ac89c6949ed0cf4a/src/ambianic/pipeline/ai/image_detection.py#L192) how this issue is addressed in the pre-processing for other models we use:
https://github.com/ambianic/ambianic-edge/blob/482d9774306ad7700a7cb905ac89c6949ed0cf4a/src/ambianic/pipeline/ai/pose_engine.py#L115

On a related topic, we need to add test coverage for pose engine to make sure that it behaves as expected when integrated with the rest of the system and it does not regress as we move forward.

**Comment by bhavikapanara** [comment]
Updated in new PR.

**Comment by ivelin** [comment]
Great. I think you are referring to https://github.com/ambianic/ambianic-edge/pull/267

Please take advantage of references to make it easier to navigate the web of issues and PRs.
https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/autolinked-references-and-urls

Also in PR's that intend to close an issue, you can use these shortcuts to automate the github workflow and minimize dangling issues:
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by ivelin** [comment]
Correct. I would like us to do a bit more work on understanding the categories of cases based on the data we have an user feedback. Once we have a good baseline of the current model accuracy, we can discuss whether it's good enough or we need to design an entirely new model. More comments in the google doc.

**Comment by bhavikapanara** [comment]
> Correct. I would like us to do a bit more work on understanding the categories of cases based on the public fall data we have and direct user feedback. Once we have a good baseline of the current model accuracy, we can discuss whether it's good enough or we need to design an entirely new model. More comments in the google doc.

Yes...it makes sense

**Comment by bhavikapanara** [comment]
@ivelin for PR #270, I got diff coverage error. 

Can you please help me to fix it?

**Comment by ivelin** [comment]
Closed #270
