### ISSUE TITLE
[BUG] DEBUG log level is no longer reflective of configuration parameter

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#257]
**Describe the bug**
Changing log level in config.yaml does not have an effect on console or log file output level.

**To Reproduce**
1. Install an ambianic-edge image
2. Set log level to DEBUG in config.yaml:

```
logging:
  file: ./data/ambianic-log.txt
  level: DEBUG
```

3. Look at  `docker-compose logs` output and `tail -f data/ambianic-log.txt`
4. See that both output INFO level messages, but not DEBUG messages.

**Expected behavior**
At a minimum the log file should be showing DEBUG level messages.

**Host environment (please complete the following information):**
 - Hardware: rpi4
 - OS: Ambianic OS
 - Container: docker
 - Version: ambianic-edge v1.12

**Comment by muka** [comment]
Thanks for reporting, the cases could be that there is a bug in the code itself or that the configuration is not loaded effectively using the defaults. Will check this out.
