### ISSUE TITLE
Fall detection should not trigger on standing up

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#258]
**Is your feature request related to a problem? Please describe.**
Currently fall detection compares the angle between body lines in two consecutive images that are 1-2 seconds apart.
If the first image captures a person that's leaning or on the ground and the second captures the person standing, the algorithm will detect a fall because the body lines would be at a bigger than 60' angle.

**Describe the solution you'd like**
It is sensible to require that the body line in the first image is close to standing position: +/- 20' from the vertical axis.

This implementation can be also covered with test cases that ensure all previous tests pass while standing up sequences do not trigger fall detection.

**Describe alternatives you've considered**
This is a stop gap improvement as we work towards an RNN fall prediction model.

**Comment by bhavikapanara** [comment]
@ivelin 

Yes...this our assumption work in many of the cases however it fails in some of the cases.

Can you please look at [this document](https://docs.google.com/document/d/1Jh7QIYgu0MHgss43ULiTLxKwFeCB54Gwaw_XGMlyt1M/edit?usp=sharing) where I have to try to create two different situations to get to know about standing position?

**Comment by ivelin** [comment]
Done.
