### ISSUE TITLE
fall detection does not use confidence_threshold parameter from config

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#261]
The config parameter `confidence_threshold ` determines the user's minimum required confidence for a detection. Currently fall detection uses a hard coded 0.25 value. See [config docs](https://docs.ambianic.ai/users/configure/).

https://github.com/ambianic/ambianic-edge/blob/f5fe48f0d03e511d748d561a57daa66c70edf8e1/src/ambianic/pipeline/ai/fall_detect.py#L87

**Comment by bhavikapanara** [comment]
Thanks, @ivelin 

I have made the changes.

**Comment by ivelin** [comment]
Can you please cross link the PR where the changes are made.
