### ISSUE TITLE
Use resenet50 or another more advanced posenet DNN

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#265]
**Is your feature request related to a problem? Please describe.**
We currently use mobilnetv1 which works, but is now outperformed by newer DNNs used in [PoseNet v2.0](https://github.com/tensorflow/tfjs-models/tree/master/posenet?linkId=69346545).

**Describe the solution you'd like**
Replace mobilnetv1 with resnet50 or a better model.

**Additional Context**
[BlazePose](https://ai.googleblog.com/2020/08/on-device-real-time-body-pose-tracking.html) is another recent development worth considering. Detects more keypoints than PoseNet 2.

**Comment by bhavikapanara** [comment]
@ivelin currently the TFLite model for `posenet` is only available in mobilnetv1.

Ref: [https://tfhub.dev/s?deployment-format=lite&q=posenet](https://tfhub.dev/s?deployment-format=lite&q=posenet)

Will look at BlazePose

**Comment by ivelin** [comment]
See this
https://github.com/rwightman/posenet-python/issues/14

**Comment by ivelin** [comment]
BlazePose also look very interesting because it takes into account the central bodyline position as a reference metric in the model design.

**Comment by ivelin** [comment]
@bhavikapanara see another recent development with impressive results: CenterNet

See TF models in the TensorFlow 2 Detection Model Zoo. Binaries in saved tf format, which can be converted to tflite format.
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

Notice the high performance and dual purpose (object + keypoints) for CenterNet Resnet50 V1 FPN Keypoints 512x512 and CenterNet Resnet50 V2 Keypoints 512x512. 

More on CenterNet and its various applications for object detection, pose keypoint estimation and object motion tracking.
https://github.com/xingyizhou/CenterNet

**Comment by ivelin** [comment]
Closing as duplicate of #274
