### ISSUE TITLE
Improve fall detection with new confidence_threshold formula

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#279]
**Is your feature request related to a problem? Please describe.**
Currently in the fall detection algorithm, confidence_thresold [applies to the average of all 17 keypoint scores](https://github.com/ambianic/ambianic-edge/blob/c418f4db5e6487aa086579ade56347e35ad12c83/src/ambianic/pipeline/ai/pose_engine.py#L166) from a pose detection model output. Upon further experimentation and user testing, it is becoming clear that this approach is sub-optimal.

In practical situations, the user whose fall we intend to detect may not be facing the camera. Or parts of the user body may be obstructed by furniture, doors or other household items.

By limiting detection to an average of all body keypoints, we cut out a number of practical situations.

**Describe the solution you'd like**
We should consider high confidence score only for the parts that are relevant to detecting a fall. In the current algorithm we use the hip-shoulder vectors (left or right). As long as there is a high level of confidence that the model detected any one of the body torso vectors, we should feed that vector to the [downward motion heuristic](https://github.com/ambianic/ambianic-edge/blob/c418f4db5e6487aa086579ade56347e35ad12c83/src/ambianic/pipeline/ai/fall_detect.py#L105).

We should end up with something like this:
- extract all hip and shoulder keypoints along with their score
- leftVectorScore = average (left hip score + left shoulder score)
- if leftVectorScore > confidence_threshold then use it in calculating angles. Otherwise skip it in this detection run.
- rightVectorScore  = average (right hip score + right shoulder score)
- if rightVectorScore > confidence_threshold then use it in calculating angles. Otherwise skip it in this detection run.
- lean_angle = get the max of the leaning angles for all of the vectors that passes the confidence_threshold test
- if lean_angle > lean_threshold, then indicate a positive fall detection

**Additional context**
We will still have to test if this change results in false positives, which we may be able to mitigate with a higher confidence_threshold.

**Comment by bhavikapanara** [comment]
@ivelin 

In PR #280, I have added the following conditions:

```
extract all hip and shoulder keypoints along with their score
leftVectorScore = average (left hip score + left shoulder score)
if leftVectorScore > confidence_threshold then use it in calculating angles. Otherwise skip it in this detection run.
rightVectorScore = average (right hip score + right shoulder score)
if rightVectorScore > confidence_threshold then use it in calculating angles. Otherwise skip it in this detection run.
lean_angle = get the max of the leaning angles for all of the vectors that passes the confidence_threshold test
if lean_angle > lean_threshold, then indicate a positive fall detection
```

However, [the line the calculate the average of all 17 keypoint scores,](https://github.com/ambianic/ambianic-edge/blob/c418f4db5e6487aa086579ade56347e35ad12c83/src/ambianic/pipeline/ai/pose_engine.py#L166) does that need to be retained? As that pose_score will be used to handle our image rotation work.

[        while (not poses or poses[0].score < min_score) and rotations:](https://github.com/ambianic/ambianic-edge/blob/c418f4db5e6487aa086579ade56347e35ad12c83/src/ambianic/pipeline/ai/fall_detect.py#L129)

**Comment by ivelin** [comment]
> @ivelin
> 
> In PR #280, I have added the following conditions:

Yes, noticed and commented. Please take a look.

> 
> ```
> extract all hip and shoulder keypoints along with their score
> leftVectorScore = average (left hip score + left shoulder score)
> if leftVectorScore > confidence_threshold then use it in calculating angles. Otherwise skip it in this detection run.
> rightVectorScore = average (right hip score + right shoulder score)
> if rightVectorScore > confidence_threshold then use it in calculating angles. Otherwise skip it in this detection run.
> lean_angle = get the max of the leaning angles for all of the vectors that passes the confidence_threshold test
> if lean_angle > lean_threshold, then indicate a positive fall detection
> ```
> 
> However, [the line the calculate the average of all 17 keypoint scores,](https://github.com/ambianic/ambianic-edge/blob/c418f4db5e6487aa086579ade56347e35ad12c83/src/ambianic/pipeline/ai/pose_engine.py#L166) does that need to be retained? As that pose_score will be used to handle our image rotation work.
> 

Great catch.

No,  we will not use this average over all keypoints. As I mentioned in the description above, we have realistic situations where parts of the body are not visible in the image at all. The model (especially resnet50) is still able to detect with high confidence the key points that are visible. We will use these high confidence points when possible and not allow the low confidence ones to affect fall detection. Once this is implemented we will test on more user data and find out if its a better heuristic than the current one. 

Along the way please keep adding unit test with user provided images that will help us prevent regression of the overall detection model as we learn and adjust the algorithm.

> [ while (not poses or poses[0].score < min_score) and rotations:](https://github.com/ambianic/ambianic-edge/blob/c418f4db5e6487aa086579ade56347e35ad12c83/src/ambianic/pipeline/ai/fall_detect.py#L129)

I think the rotation should be conditioned on whether or not we have a valid body vector from a previous rotation. If we do, then no need to rotate, but if we don't have a body vector that meets the confidence threshold criteria (the new one that is - each keypoint of a vector: hip and shoulder are above the minimum score (confidence_threshold)) then we apply the next rotation. 

Making sense?

**Comment by ivelin** [comment]
@bhavikapanara I found a few public sources with helpful training data.

[This research study](https://www.youtube.com/watch?v=sw2-Z4GbK54&feature=emb_logo) concludes that falls last anywhere between 600 and 800ms. We [currently expect 1 second gap between frames](https://github.com/ambianic/ambianic-edge/blob/527ed833980dbde58726db5f9edc5a2694c52258/src/ambianic/pipeline/ai/fall_detect.py#L47), which seems to be a reasonable choice that should be long enough to capture an image before and after a fall. The question remains open how to handle sequence of frames that may come in (before and middle) of a fall or (middle and after) a fall. In these cases the fall may be incomplete between the two comparison frames and we won't detect it with the current algorithm. Something to think about. May we look 2 frames back instead of 1, which ensures that a fall is certainly captured either in the (1,2), (2,3) or (1,3) pair of frames. Thoughts?

**Comment by ivelin** [comment]
@bhavikapanara As you requested, [here is public training data with sequence images from various elderly falls](https://drive.google.com/drive/folders/1Wai7dGLfrsoPUWdw4JVsaJ4CSepBhBdn?usp=sharing). Please include a variation of these images in the testsuite to ensure we have reasonable coverage of realistic use cases.
