### ISSUE TITLE
[BUG] address LGTM bot warnings for image_boundingBox_detection

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#300]
**Describe the bug**
https://lgtm.com/projects/g/ambianic/ambianic-edge/latest/files/src/ambianic/pipeline/ai/image_boundingBox_detection.py?sort=name&dir=ASC&mode=heatmap

**Comment by bhavikapanara** [comment]
Fix in this PR #296

**Comment by ivelin** [comment]
@bhavikapanara  Please don't mix the scope of PRs. Makes things harder to review and manage. Hard to tell which code change in the PR applies to which issue. Please submit a fix for each issue in a separate PR. If the issue is too big, submit multiple PRs with clear small scope. Take a look at [this blog post](https://www.netlify.com/blog/2020/03/31/how-to-scope-down-prs/).

**Comment by bhavikapanara** [comment]
Ok.
Actually, there was very small changes are needed for this issue so I have updated it in current PR. It is fine I will create separate PR for each issue.

**Comment by ivelin** [comment]
OK, I see. If you were referring to the minor LGTM warnings, then that might be OK.
