### ISSUE TITLE
Autogen and publish REST API docs for ambianic edge

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#335]
**Is your feature request related to a problem? Please describe.**
Currently the project docs do not include the REST API for ambianic edge.

**Describe the solution you'd like**

- Define with Open API spec the edge API. 
- Publish the docs. 
- Implement CI tests.
- Provide examples in docs
- Explain how it works with p2p and PWA views

Tools to consider:
- https://flask-apispec.readthedocs.io/en/latest/
- https://github.com/tiangolo/fastapi
- https://github.com/OpenAPITools

**Describe alternatives you've considered**
FastAPI has emerged as a popular way to write REST APIs in Python. It has built-in support for testing and auto-docs.
https://github.com/tiangolo/fastapi

**Comment by PhillipAmes** [comment]
I would like to take this on.  I am currently studying and practicing API documentation with a docs-as-code approach and would like to volunteer on this.

**Comment by ivelin** [comment]
Sounds good, @PhillipAmes . I transferred this task to you. Give it a shot!

**Comment by vickywane** [comment]
@PhillipAmes Thanks for offering to help. 

This somewhat relates to [this pull request](https://github.com/ambianic/ambianic-edge/pull/343) which is currently being worked on and almost ready for release. You might want to have a look at it first.

CC @ivelin

**Comment by ivelin** [comment]
That is true. 

For an initial PR however, @PhillipAmes can focus on the already released and stable edge REST API. [Its test cases](https://github.com/ambianic/ambianic-edge/blob/master/tests/test_flaskr.py) are currently the best documentation for it.

**Comment by vickywane** [comment]
Alright @ivelin . 

@PhillipAmes Come join the Ambianic Slack channel and feel free to ping me if you need any help.

**Comment by PhillipAmes** [comment]
I think I've nearly got the development environment going.  I have worked through some of the FastAPI tutorial and I think that once I've got Ambianic Edge going I'll be able to start adding the decorators FastAPI needs to generate the OAS/docs. I will keep updating as I make progress.  I'm sure I'll also have questions soon too.

**Comment by PhillipAmes** [comment]
Spent some time this evening trying to get Ambianic -Edge running in docker on my machine.  Was not successful.  I will keep trying.  I also tried launching a uvicorn server on just the file flaskr.py with the dependencies commented out, to see if the decorators already in place in flaskr.py would give FastAPI what it needed to generate the OAS.  That didn't work.  I'm learning a lot and I'll keep trying and posting my progress.  Questions to follow too.

**Comment by PhillipAmes** [comment]
You're welcome, I'm happy to be here and learning so much.  

Today I solved an error message that I was getting yesterday.  When attempting to start the development container with "./ambianic-debug.sh" I got the following error:

> the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

And I fixed it by doing exactly what the message said, I went into ambianic-debug.sh and put "winpty" before docker on line 35.  Bash then showed I was in the container.  

Next I changed directory to /workspace/ and tried running "./src/run-dev.sh" and got the following error messages:

> ./src/run-dev.sh: line 2: cd: $'/workspace\r': No such file or directory 

> /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_
bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_byte
s is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
 is not a valid editable requirement. It should either be a path to a local project or a VCS URL (begi
nning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git
+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+ht
tps, svn+svn, svn+file).
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
/usr/bin/python3: No module named ambianic

I was able to run "./tests/run-tests.sh" and got the following feedback:

> ./tests/run-tests.sh: line 1: $'\r': command not found
: invalid options.sh: line 3: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./tests/run-tests.sh: line 4: $'\r': command not found
./tests/run-tests.sh: line 12: $'\r': command not found
./tests/run-tests.sh: line 16: $'\r': command not found
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_
bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_byte
s is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting pytest
  Downloading pytest-6.2.4-py3-none-any.whl (280 kB)
     |████████████████████████████████| 280 kB 103 kB/s
Collecting iniconfig
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting pluggy<1.0.0a1,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting py>=1.8.2
  Downloading py-1.10.0-py2.py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 141 kB/s
Requirement already satisfied: importlib-metadata>=0.12 in /usr/local/lib/python3.7/dist-packages (fro
m pytest) (3.7.3)
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting packaging
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 178 kB/s
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.7/dist-packages (from pytest) (
20.3.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-met
adata>=0.12->pytest) (3.4.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (fro
m importlib-metadata>=0.12->pytest) (3.7.4.3)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 145 kB/s
Installing collected packages: pyparsing, toml, py, pluggy, packaging, iniconfig, pytest
Successfully installed iniconfig-1.1.1 packaging-20.9 pluggy-0.13.1 py-1.10.0 pyparsing-2.4.7 pytest-6
.2.4 toml-0.10.2
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_
bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_byte
s is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting codecov
  Downloading codecov-2.1.11-py2.py3-none-any.whl (16 kB)
Collecting coverage
  Downloading coverage-5.5-cp37-cp37m-manylinux2010_x86_64.whl (242 kB)
     |████████████████████████████████| 242 kB 640 kB/s
Requirement already satisfied: requests>=2.7.9 in /usr/local/lib/python3.7/dist-packages (from codecov
) (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from reque
sts>=2.7.9->codecov) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from r
equests>=2.7.9->codecov) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requ
ests>=2.7.9->codecov) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=
2.7.9->codecov) (2.10)
Installing collected packages: coverage, codecov
Successfully installed codecov-2.1.11 coverage-5.5
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_
bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_byte
s is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting pytest-cov
  Downloading pytest_cov-2.11.1-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: coverage>=5.2.1 in /usr/local/lib/python3.7/dist-packages (from pytest-
cov) (5.5)
Requirement already satisfied: pytest>=4.6 in /usr/local/lib/python3.7/dist-packages (from pytest-cov)
 (6.2.4)
Requirement already satisfied: pluggy<1.0.0a1,>=0.12 in /usr/local/lib/python3.7/dist-packages (from p
ytest>=4.6->pytest-cov) (0.13.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from pytest>=4.6->
pytest-cov) (20.9)
Requirement already satisfied: importlib-metadata>=0.12 in /usr/local/lib/python3.7/dist-packages (fro
m pytest>=4.6->pytest-cov) (3.7.3)
Requirement already satisfied: py>=1.8.2 in /usr/local/lib/python3.7/dist-packages (from pytest>=4.6->
pytest-cov) (1.10.0)
Requirement already satisfied: toml in /usr/local/lib/python3.7/dist-packages (from pytest>=4.6->pytes
t-cov) (0.10.2)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.7/dist-packages (from pytest>=4
.6->pytest-cov) (20.3.0)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.7/dist-packages (from pytest>=4.6->
pytest-cov) (1.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-met
adata>=0.12->pytest>=4.6->pytest-cov) (3.4.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (fro
m importlib-metadata>=0.12->pytest>=4.6->pytest-cov) (3.7.4.3)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packag
ing->pytest>=4.6->pytest-cov) (2.4.7)
Installing collected packages: pytest-cov
Successfully installed pytest-cov-2.11.1
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_
bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_byte
s is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting pylint
  Downloading pylint-2.8.2-py3-none-any.whl (357 kB)
     |████████████████████████████████| 357 kB 32 kB/s
Collecting isort<6,>=4.2.5
  Downloading isort-5.8.0-py3-none-any.whl (103 kB)
     |████████████████████████████████| 103 kB 69 kB/s
Collecting mccabe<0.7,>=0.6
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Requirement already satisfied: toml>=0.7.1 in /usr/local/lib/python3.7/dist-packages (from pylint) (0.
10.2)
Collecting astroid<2.7,>=2.5.6
  Downloading astroid-2.5.6-py3-none-any.whl (219 kB)
     |████████████████████████████████| 219 kB 44 kB/s
Collecting typed-ast<1.5,>=1.4.0
  Downloading typed_ast-1.4.3-cp37-cp37m-manylinux1_x86_64.whl (743 kB)
     |████████████████████████████████| 743 kB 45 kB/s
Collecting lazy-object-proxy>=1.4.0
  Downloading lazy_object_proxy-1.6.0-cp37-cp37m-manylinux1_x86_64.whl (55 kB)
     |████████████████████████████████| 55 kB 53 kB/s
Collecting wrapt<1.13,>=1.11
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Building wheels for collected packages: wrapt
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.12.1-cp37-cp37m-linux_x86_64.whl size=73437 sha256=981da2d
8d4fe4483108f18a27dfc683d323808106712e0a2d9d12615300ce1a4
  Stored in directory: /root/.cache/pip/wheels/62/76/4c/aa25851149f3f6d9785f6c869387ad82b3fd37582fa814
7ac6
Successfully built wrapt
Installing collected packages: wrapt, typed-ast, lazy-object-proxy, mccabe, isort, astroid, pylint
Successfully installed astroid-2.5.6 isort-5.8.0 lazy-object-proxy-1.6.0 mccabe-0.6.1 pylint-2.8.2 typ
ed-ast-1.4.3 wrapt-1.12.1
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_
bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_byte
s is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
 is not a valid editable requirement. It should either be a path to a local project or a VCS URL (begi
nning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git
+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+ht
tps, svn+svn, svn+file).
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Script location: ./tests
./tests/run-tests.sh: line 26: cd: $'./tests\r/../\r': No such file or directory
PWD=/workspace
>======================================== test session starts >=========================================
>platform linux -- Python 3.7.3, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /workspace
plugins: cov-2.11.1
collected 0 items

>======================================= no tests ran in 0.07s >========================================
>ERROR: file or directory not found: tests/

>./tests/run-tests.sh: line 29: $'\r': command not found
>./tests/run-tests.sh: line 36: $'\r': command not found


I'll be back at it tomorrow.  Thanks again for the opportunity to help with this, I feel like I get closer to the docs at the end of the tunnel everyday.

**Comment by PhillipAmes** [comment]
Today I spent some time with the FastAPI docs, working through their examples and getting slightly more familiar with them. Then I tried getting the development environment up and running again.  I had the same results and error messages as yesterday, although much more quickly.

**Comment by ivelin** [comment]
Can you please share the OS you are running on?

**Comment by PhillipAmes** [comment]
I should have thought of that.  I'm on Windows 10.

**Comment by ivelin** [comment]
OK, you may be the first person to try this on a windows machine.
You have two immediate options:
1. Work through the errors and update the scripts to work on Windows.
2. Try the gitpod cloud
<https://gitpod.io/#https://github.com/ambianic/ambianic-edge> environment.
I've been using this option happily for months.

Here is the current guide
<https://docs.ambianic.ai/developers/development-environment/> on setting
up your dev environment. Not sure if it will be very helpful for Windows ,
but if you choose to proceed with the Windows route, maybe you can
contribute a section on that.

**Comment by PhillipAmes** [comment]
Hello,  I've been chipping away at this and I have a few higher level questions.  I'm not a developer, I'm a technical writer transitioning into REST api documentation so I do need a little help with contextualization. 

My efforts so far have centered around flaskr.py, are there other source files that include other endpoints?  

What are the endpoints for Ambianic-Edge? If it's running on a raspberry pi on my home network is it exposing a URL? If yes, what is the URL?

**Comment by ivelin** [comment]
You are looking at the correct file
<https://github.com/ambianic/ambianic-edge/blob/master/src/ambianic/webapp/flaskr.py>.
It's the only place where ambianic edge exposes REST endpoints.

The endpoints are exposed on http://localhost:8778 by default
<https://github.com/ambianic/ambianic-edge/blob/440cebc2b53da25d7cbb07c873bc1cf603010640/src/ambianic/webapp/flaskr.py#L37>
.

**Comment by PhillipAmes** [comment]
Today I started the development environment in gitpod, and ran the tests with "python3 -m pytest --cov=ambianic --cov-report=term tests/".  I got a message saying there was a port exposed, I found the toggle in gitpod to make it public, although gitpod listed it as "not served", I'm not sure what that means. I then ran "hostname -I" and "ip addr show" and they agreed on the ip address.  

So I went to postman to make requests.  I wasn't able to get a response.  It could be due to Postman not working with custom ports, or the 'not served' note from above.  I also tried with curl from the command line, I wasn't able to get a response there either.  

I will keep chipping away at this.

**Comment by ivelin** [comment]
"python3 -m pytest... " will run the test suite and end without leaving the
REST API running.

If you'd like to manually access the REST API on gitpod's virtual localhost
port 8778, you should run the ambianic edge serve like this:

"python3 -m ambianic"

After a moment you will get a browser pop up button in gitpod. When you
open a preview, you will see a simple message:
"Ambianic Edge! Helpful AI for home and business automation."

See attached screenshot:

[image: Screen Shot 2021-05-17 at 4.56.47 PM.png]

**Comment by PhillipAmes** [comment]
I was able to make requests with cURL.  I am going to continue with getting familiar with the endpoints and start ramping up study on the different ways to autogenerate the OAS (FastAPI, flaskapispec, etc). 

I'll be back at it tomorrow, thank you for your help and the opportunity to help!

**Comment by ivelin** [comment]
Glad to see you are making progress. Keep us posted.

**Comment by PhillipAmes** [comment]
Today I took a look at some of the openapi spec (f.k.a. swagger) generating tools listed in the issue description above, dependencies, documentation, approach, etc.  I'm continuing to work on this and will be back at it tomorrow.

**Comment by PhillipAmes** [comment]
Today as practice for this issue I used Swagger UI to display documentation generated from an OpenAPI Specification (swagger) file.  

I'll be back at it tomorrow.

**Comment by PhillipAmes** [comment]
Today I updated my fork to current, added the FastAPI import statement, added a decorator and tried to get it running in gitpod to see what would happen.  The build failed, I'm not able to include the error messages. 

I will be back at it tomorrow.

**Comment by ivelin** [comment]
FastAPI <https://github.com/tiangolo/fastapi> is an alternative web server
to Flask. We currently use Flask <https://github.com/pallets/flask>.
Importing FastAPI into a Flask based application won't work.

If your intention is to add OpenAPI decorators to our REST endpoints and
generate docs from these, you may want to look at:
https://github.com/flasgger/flasgger
https://kanoki.org/2020/07/18/python-api-documentation-using-flask-swagger/

If you'd like to switch us from Flask to FastAPI, you would have to
refactor some code in flaskr.py
<https://github.com/ambianic/ambianic-edge/blob/master/src/ambianic/webapp/flaskr.py>
and
other files that reference the Flask APIs.

**Comment by PhillipAmes** [comment]
I would like to generate the OpenAPI specification manually and then use a static site generator to make it available to users.  I would like to include some related topics where appropriate, things like authorization and authentication, common use cases and, rate limiting and thresholds.

**Comment by ivelin** [comment]
> I would like to generate the OpenAPI specification manually and then use a static site generator to make it available to users. I would like to include some related topics where appropriate, things like authorization and authentication, common use cases and, rate limiting and thresholds.

@PhillipAmes are you still working on this issue?

**Comment by PhillipAmes** [comment]
Hey!

I had to have reconstructive surgery after my accident. I only got the
sling off a couple days ago. It's been on my mind but I haven't done
anything yet.

From what I remember I think the thing to do is make the oas(swagger)
manually. I've done that for a different api before my accident and it's
not that hard. The ambianic api is pretty straightforward as far as I can
tell.

I'm sorry I haven't been working on this.

Phillip Ames

**Comment by ivelin** [comment]
@PhillipAmes No worries at all. Hope you are recovering fast.
Just wanted to check on status because there is interest from new contributors. 
I will reassign it now so we can keep making progress. You are more than welcome to re-join on this or another issue as soon as you feel better.
