### ISSUE TITLE
[BUG] 'Unable to set pipeline to playing state ', 'file:///workspace/ambianic-edge/tests/pipeline/avsource/test2-cam-person1.mkv'

### ISSUE THREAD

**Issue by vickywane** [ambianic/ambianic-edge#381]
**Describe the bug**
When using a docker image of the ambianic-edge in development mode, an exception is thrown when the PWA attempts to connects with the edge-device.  

The log from the handled exception reads: 

```
WARNING /workspace/src/ambianic/pipeline/avsource/gst_process.py.run(396): GST loop exited with error: ('Unable to set pipeline to playing state ', 'file:///workspace/ambianic-edge/tests/pipeline/avsource/test2-cam-person1.mkv'). 
``` 

![Screenshot_20210914_154530](https://user-images.githubusercontent.com/29664439/133280866-9a25999d-e13e-4a7a-912b-09aaab61c1d5.png)

This further causes the peer connection to throw an exception that reads;
```
 AttributeError: module 'dns.message' has no attribute 'QueryMessage'
```

![Screenshot_20210914_153817](https://user-images.githubusercontent.com/29664439/133280895-4d86aeb7-74f9-464a-bcf9-2fe5f7d35fad.png)

**To Reproduce**
1. Clone the edge-device repository
2. Run the `./ambianic.start.sh` script pull the edge docker image and run the application
3. Start a peer connection using the python `peerjs` package by running `python3 -m peerjs.ext.http_proxy`

**Expected behavior**
A connection with the ambianic-edge docker image should be successfully established with the PWA .

**Host environment (please complete the following information):**
 - Hardware: Manjaroo
 - Docker version: Docker version 20.10.8, build 3967b7d28
- Python version: Python 3.9.6

Cc: @ivelin

**Comment by vickywane** [comment]
Troubleshooting this further, the exception seems to be from the pre-recorded video that is displayed automatically when the PWA connects to the edge device without the edge device video feeds being set.

**Comment by ivelin** [comment]
Try the gitpod environment that I documented. It's possible that your local
environment has dependencies that are out of sync. Hard to debug. Let's all
use the same dev environment to be more productive.

https://docs.ambianic.ai/developers/e2e-manual-testing/

**Comment by ivelin** [comment]
Did you try fixing the path ot the video file or running in gitpod?

**Comment by vickywane** [comment]
> Did you try fixing the path ot the video file or running in gitpod?

- I couldnt get the PWA to connect with Gitpod, so I can't say if this issue persists with Gitpod.
- The video path is not broken, the video exists. 

My temporary workaround was to revert back to an old git commit hash when Flask was being used. This issue does not persist there.
