### ISSUE TITLE
Push notification to user

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#50]
- [ ] notify web app (PWA Push Notification) that new samples are available to show to users.
- [ ] notify external notification handler (e.g. IFTTT, Zapier, MQTT) that allows integration with a wide variety of end points.

**Comment by ivelin** [comment]
Related resources:

https://www.pushpro.io/blog/pwa-push-notifications-for-progressive-web-apps

https://platform.ifttt.com/docs#3-describe-your-queries-triggers-and-actions

**Comment by ivelin** [comment]
@muka posted a few relevant resources above as I'm digging deeper into the notifications feature design.

Current thinking is to introduce a `trigger_notification` parameter to the `save_detections` pipeline element. It will have three possible values: always, positive_only, negative_only. Meaning that a notification will be trigger every time a detection event is saved, or only when a positive event is detected or only when a negative is detected (e.g. when a positive detection is no longer ongoing).

I also thought about having a separate notification element, but since  a notification should be just the minimum information without revealing any privacy details, the user will have to be able to pull details from the edge device, which requires the saved event data.

Thoughts?

**Comment by ivelin** [comment]
@muka  The shoutrrr project looks relevant. From the watchdog author. https://github.com/containrrr/shoutrrr

**Comment by muka** [comment]
Great finding! Will look into those libraries. Planning to work over it on the next days
