### ISSUE TITLE
[FEATURE] SMS notifications

### ISSUE THREAD

**Issue by mchapman67** [ambianic/ambianic-edge#87]
- Why
   
   It would be beneficial to add an ability to send an SMS alert when the system detects an event 
   such as a suspicious person, known person, or other event (worker has not returned to 
   workstation after a pre-set time limit).

- How
   
   This functionality might be achieved through the use of Twilio's webhooks

**Comment by ivelin** [comment]
This request makes sense. Adding to roadmap backlog. Thank you!

**Comment by ivelin** [comment]
@mchapman67 just FYI. @telecomsxchange will help with the SMS connection feature.

**Comment by mchapman67** [comment]
That’s great news... I noticed the pull request for this  earlier today.

**Comment by ivelin** [comment]
Related to #50, #68 and #55 .
